PROJECT_NAME = 'Jiyu Immunodeficiency Virus'
MAJOR_VER, MINOR_VER = 0, 3
RELEASE_STAGE = 'a1'
VERSION = f'{MAJOR_VER}.{MINOR_VER}{RELEASE_STAGE}'
FULL_VERSION = f'{PROJECT_NAME} v{VERSION}'
UPDATE_URL = "https://api.github.com/repos/Errorsia/PJIV-pre/releases/latest"
E_CLASSROOM_NAME = 'studentmain'
E_CLASSROOM_PROGRAM_NAME = E_CLASSROOM_NAME + '.exe'
# CODE_NAME = ''
# NICKNAME = ''